#!/bin/bash
# https://github.com/shyiko/ktlint pre-commit hook

export PATH=/usr/local/bin:$PATH

echo "Running formatter"
gradle ktlintFormat

echo "Running lint check..."
gradle ktlint

status=$?
# return 1 exit code if running checks fails
[ $status -ne 0 ] && exit 1
exit 0
