#!/bin/bash
# https://github.com/shyiko/ktlint pre-commit hook

export PATH=/usr/local/bin:$PATH

echo "Running linter"
gradle ktlintFormat

status=$?
# return 1 exit code if running checks fails
[ $status -ne 0 ] && exit 1
exit 0
