#!/bin/bash
# https://github.com/shyiko/ktlint pre-commit hook

export PATH=/usr/local/bin:$PATH

echo "Running lint check..."
gradle ktlint

status=$?
# return 1 exit code if running checks fails
[ $status -ne echo "Running formatter"
              gradle ktlintFormat ] && exit 1
exit 0
