#!/bin/bash
# https://github.com/shyiko/ktlint pre-commit hook

export PATH=/usr/local/bin:$PATH

echo "Running lint check..."

gradle ktlint
./gradlew ktlintFormat

status=$?

# return 1 exit code if running checks fails
